using CommunityToolkit.Maui;
using Eds.Core.App;
using Eds.Core.Crypto.Native;
using Eds.Core.Locations;
using Eds.Core.Services;
using Eds.Core.Settings;
using Eds.Maui.Services;
using Eds.Maui.ViewModels;
using Eds.Maui.Views;
using Microsoft.Extensions.Logging;

namespace Eds.Maui;

public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        // Ensure the native crypto library resolves correctly on every head.
        NativeLibraryResolver.EnsureRegistered();

        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
#if AVALONIA_DESKTOP
            // Render the MAUI UI through Avalonia on the desktop (net11.0) head —
            // this is what enables Linux (and drawn Windows/macOS). The Avalonia
            // Application + bootstrap are source-generated by
            // Avalonia.Controls.Maui.Desktop, so no manual AppBuilder is needed.
            .UseAvaloniaApp()
#endif
            .UseMauiCommunityToolkit();

        // --- platform services -----------------------------------------
        builder.Services.AddSingleton<IExternalFileOpener, MauiExternalFileOpener>();
        // Real secret-store-backed key (Android Keystore / iOS/macOS Keychain / Windows DPAPI).
        // Falls back to the insecure Preferences provider only if the store is unavailable.
        builder.Services.AddSingleton<IProtectionKeyProvider, SecureStoreProtectionKeyProvider>();
#if ANDROID
        builder.Services.AddSingleton<IOperationNotifier, AndroidOperationNotifier>();
        builder.Services.AddSingleton<IForegroundOperationService, AndroidForegroundOperationService>();
#else
        builder.Services.AddSingleton<IOperationNotifier, NoopOperationNotifier>();
        builder.Services.AddSingleton<IForegroundOperationService, NoopForegroundOperationService>();
#endif

        // --- application core (platform-independent) --------------------
        builder.Services.AddSingleton<ISettings>(_ =>
            new JsonFileSettings(Path.Combine(FileSystem.AppDataDirectory, "eds-settings.json")));
        builder.Services.AddSingleton(sp => new EdsAppController(
            sp.GetRequiredService<ISettings>(),
            externalOpener: sp.GetRequiredService<IExternalFileOpener>()));

        // --- pages / view models ---------------------------------------
        builder.Services.AddSingleton<LocationsViewModel>();
        builder.Services.AddSingleton<LocationsPage>();

        builder.Services.AddTransient<OpenViewModel>();
        builder.Services.AddTransient<OpenPage>();

        builder.Services.AddTransient<VaultBrowserViewModel>();
        builder.Services.AddTransient<VaultBrowserPage>();

        builder.Services.AddTransient<ChangePasswordViewModel>();
        builder.Services.AddTransient<ChangePasswordPage>();

        builder.Services.AddTransient<CreateViewModel>();
        builder.Services.AddTransient<CreatePage>();

        builder.Services.AddSingleton<SettingsViewModel>();
        builder.Services.AddSingleton<SettingsPage>();

        builder.Services.AddSingleton<MainViewModel>();
        builder.Services.AddSingleton<MainPage>();

#if DEBUG
        builder.Logging.AddDebug();
#endif

        var app = builder.Build();

        // Bridge DI to platform-instantiated components (e.g. the SAF provider),
        // and attach the (insecure placeholder) protection-key provider.
        AppServices.Services = app.Services;
        app.Services.GetRequiredService<EdsAppController>().ProtectionKeyProvider =
            app.Services.GetRequiredService<IProtectionKeyProvider>();

        return app;
    }
}
