using Eds.Core.Locations;
using Eds.Core.Services;
using Eds.Maui.Heads.Avalonia;
using Eds.Maui.Services;

namespace Eds.Maui;

/// <summary>
/// Platform registration for the Avalonia desktop head (net11.0 — Linux and drawn
/// Windows/macOS). The Avalonia MAUI backend renders the MAUI UI, but the preview
/// MAUI Essentials assembly is a reference-only stub, so pickers / secret store /
/// launcher are provided by Avalonia-native or BCL implementations here.
///
/// This file is compiled ONLY for net11.0 (routed by the csproj), so none of these
/// preview shims leak into the native MAUI builds.
/// </summary>
public static partial class MauiProgram
{
    internal static void RegisterPlatformServices(MauiAppBuilder builder)
    {
        // Render the MAUI UI through Avalonia. The Avalonia Application + bootstrap
        // are source-generated by Avalonia.Controls.Maui.Desktop; no manual AppBuilder.
        builder.UseAvaloniaApp();

        builder.Services.AddSingleton<IExternalFileOpener, DesktopExternalFileOpener>();
        builder.Services.AddSingleton<IFolderPicker, AvaloniaFolderPicker>();
        builder.Services.AddSingleton<IFilePickerService, AvaloniaFilePickerService>();

        // Essentials SecureStorage/Preferences throw on this head → file-based key.
        builder.Services.AddSingleton<IProtectionKeyProvider, FileProtectionKeyProvider>();

        // No Android notifier / foreground service on desktop.
        builder.Services.AddSingleton<IOperationNotifier, NoopOperationNotifier>();
        builder.Services.AddSingleton<IForegroundOperationService, NoopForegroundOperationService>();
    }
}
